### ISSUE TITLE
Failed to build wheel on windows

### ISSUE THREAD

**Issue by SquashyHydra** [pitrou/pickle5-backport#33]
I have been struggling to install pickle5 on my windows machine, I have gone through the necessary steps, upgrading my setuptools and installing Microsoft build tools.
![image_2023-07-24_202559149](https://github.com/pitrou/pickle5-backport/assets/89506339/95c90ffb-b4c4-4fe1-ae17-f237227e0a19)
I have gradually tried installing different build tool options, but with no luck, as well as the [prebuild wheels](https://pypi.org/project/pickle5/#files) provided on pypi.org.
![image_2023-07-24_203027313](https://github.com/pitrou/pickle5-backport/assets/89506339/9ac008e2-3e23-4e1f-920f-7538a2f2c4c8)
![image_2023-07-24_203040014](https://github.com/pitrou/pickle5-backport/assets/89506339/55c626d6-6253-4dd3-835e-cbc8e920068a)
And when ever I attempt to build the wheel I get this error:
```
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pickle5
      copying pickle5\pickle.py -> build\lib.win-amd64-cpython-311\pickle5
      copying pickle5\pickletools.py -> build\lib.win-amd64-cpython-311\pickle5
      copying pickle5\__init__.py -> build\lib.win-amd64-cpython-311\pickle5
      creating build\lib.win-amd64-cpython-311\pickle5\test
      copying pickle5\test\pickletester.py -> build\lib.win-amd64-cpython-311\pickle5\test
      copying pickle5\test\test_pickle.py -> build\lib.win-amd64-cpython-311\pickle5\test
      copying pickle5\test\test_picklebuffer.py -> build\lib.win-amd64-cpython-311\pickle5\test
      copying pickle5\test\__init__.py -> build\lib.win-amd64-cpython-311\pickle5\test
      running build_ext
      building 'pickle5._pickle' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\pickle5
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Python311\include" "-IC:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcpickle5/_pickle.c /Fobuild\temp.win-amd64-cpython-311\Release\pickle5/_pickle.obj
      _pickle.c
      pickle5/_pickle.c(464): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(491): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(542): error C2105: '--' needs l-value
      pickle5/_pickle.c(552): error C2105: '++' needs l-value
      pickle5/_pickle.c(582): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(599): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(1285): warning C4013: '_PyObject_CallNoArg' undefined; assuming extern returning int
      pickle5/_pickle.c(1285): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
      pickle5/_pickle.c(1937): warning C4013: '_PySys_GetObjectId' undefined; assuming extern returning int
      pickle5/_pickle.c(1937): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
      pickle5/_pickle.c(2255): warning C4013: '_PyFloat_Pack8' undefined; assuming extern returning int
      pickle5/_pickle.c(4452): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
      pickle5/_pickle.c(5428): warning C4013: '_PyFloat_Unpack8' undefined; assuming extern returning int
      pickle5/_pickle.c(6178): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(6535): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(6541): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(6663): error C2106: '=': left operand must be l-value
      pickle5/_pickle.c(6668): error C2106: '=': left operand must be l-value
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pickle5
  Running setup.py clean for pickle5
Failed to build pickle5
ERROR: Could not build wheels for pickle5, which is required to install pyproject.toml-based projects

```
Can anyone provide any information on this error it would be extremely help-full.

**Comment by pitrou** [comment]
"""This package backports all features and APIs added in the pickle module in Python 3.8.3, including the [PEP 574](https://www.python.org/dev/peps/pep-0574/) additions. It should work with Python 3.5, 3.6 and 3.7."""

=> You don't need pickle5 with Python 3.11
