### ISSUE TITLE
Failed Building wheel for pickle5

### ISSUE THREAD

**Issue by shubh28012004** [pitrou/pickle5-backport#34]

**Comment by Keshav7m** [comment]
same, need help on that.

**Comment by dsidlo** [comment]
I'm getting the following errors when during the build...
```
building 'pickle5._pickle' extension
      creating build/temp.linux-x86_64-cpython-312/pickle5
      gcc -pthread -B /home/dsidlo/anaconda3/envs/pricepredict/compiler_compat -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/dsidlo/anaconda3/envs/pricepredict/include -fPIC -O2 -isystem /home/dsidlo/anaconda3/envs/pricepredict/include -fPIC -I/home/dsidlo/anaconda3/envs/pricepredict/include/python3.12 -c pickle5/_pickle.c -o build/temp.linux-x86_64-cpython-312/pickle5/_pickle.o -std=c99
      pickle5/_pickle.c: In function ‘Pdata_New’:
      pickle5/_pickle.c:464:19: error: lvalue required as left operand of assignment
        464 |     Py_SIZE(self) = 0;
            |                   ^
      pickle5/_pickle.c: In function ‘Pdata_clear’:
      pickle5/_pickle.c:491:19: error: lvalue required as left operand of assignment
        491 |     Py_SIZE(self) = clearto;
            |                   ^
      pickle5/_pickle.c: In function ‘Pdata_pop’:
      pickle5/_pickle.c:542:23: error: lvalue required as decrement operand
        542 |     return self->data[--Py_SIZE(self)];
            |                       ^~
      pickle5/_pickle.c: In function ‘Pdata_push’:
      pickle5/_pickle.c:552:29: error: lvalue required as increment operand
        552 |     self->data[Py_SIZE(self)++] = obj;
            |                             ^~
      pickle5/_pickle.c: In function ‘Pdata_poptuple’:
      pickle5/_pickle.c:582:19: error: lvalue required as left operand of assignment
        582 |     Py_SIZE(self) = start;
            |                   ^
      pickle5/_pickle.c: In function ‘Pdata_poplist’:
      pickle5/_pickle.c:599:19: error: lvalue required as left operand of assignment
        599 |     Py_SIZE(self) = start;
            |                   ^
      In file included from pickle5/_pickle.c:719:
....
```

Is this a gcc version issue?

**Comment by pitrou** [comment]
Please, do yourself a favor and read the README:
> This package backports all features and APIs added in the pickle module in Python 3.8.3, including the [PEP 574](https://www.python.org/dev/peps/pep-0574/) additions. It should work with Python 3.5, 3.6 and 3.7.
